name: Tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        luaVersion: ['5.1', '5.2', '5.3', '5.4', 'luajit-2.1', 'luajit-openresty']
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v11
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: "install luacheck"
        run: luarocks install luacheck

      - name: "install laura"
        run: luarocks install laura

      - name: test
        run: laura test/

      - name: lint
        run: luacheck ./*.lua
